name: app_clima
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: 0.20.2
  geolocator: ^13.0.2
  # Firebase (sin Functions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  flutter_gen: ^5.12.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/peru_cities.json
